version: "3"
services:
  cascade_builder:
    image: espressif/idf:release-v5.1
    container_name: cascade_builder
    user: "1000:1000"
    volumes:
      - .:/app/
    environment:
      - HOME=/tmp
    working_dir: /app/
    command: idf.py build
  cascade_flasher:
    image: espressif/idf:release-v5.1
    container_name: cascade_flasher
    user: "1000:1000"
    volumes:
      - .:/app/
    environment:
      - HOME=/tmp
    working_dir: /app/
    command: idf.py flash -p /dev/ttyACM1
    devices:
     - "/dev/ttyACM1:/dev/ttyACM1"
